openapi: "3.0.0"
info:
  title: API Auth Sitionix
  description: Api specification for auth service
  version: 0.0.3
  contact:
    name: APP Sitionix
servers:
  - description: Localhost (dev only)
    url: 'http://localhost:8080/athssox'
tags:
  - name: User
paths:
  /api/v2/user:
    post:
      summary: user
      operationId: userOperation
      tags:
        - User
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
            format: string
        - name: password
          in: query
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: User
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          format: string
        password:
          type: string
          format: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string