openapi: "3.0.0"
info:
  title: API Auth Sitionix
  description: Api specification for auth service
  version: 0.0.3
  contact:
    name: APP Sitionix
servers:
  - description: Localhost (dev only)
    url: 'http://localhost:8080/athssox'
tags:
  - name: User
paths:
  /api/v1/user:
    post:
      description: Service that create user
      summary: API for user creation
      operationId: createUser
      tags:
        - User
      requestBody:
        description: User body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
          content:
            application/json:
              example: 'Success'
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
          content:
            text/plain:
              example: 'Invalid request parameters, try again.'
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            text/plain:
              example: "An unexpected error occurred on the server."
              schema:
                type: string

components:
  schemas:
    User:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: Edvard
        password:
          type: string
          example: qwerty1234
