openapi: 3.0.0
info:
  title: API Auth Sitionix
  version: 0.1.11
  contact:
    name: APP Sitionix
servers:
  - description: Localhost (dev only)
    url: 'http://localhost:8080/athssox'
tags:
  - Dummy
paths:
  /api/v1/dummy:
    get:
      summary: Dummy summary
      operationId: dummyOperation
      tags:
        - Dummy
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string