openapi: "3.0.0"
info:
  title: API Auth Sitionix
  description: Api specification for auth service
  version: 0.0.3
  contact:
    name: APP Sitionix
servers:
  - description: Localhost (dev only)
    url: 'http://localhost:8080/athssox'
tags:
  - name: User
paths:
  /api/v1/user:
    post:
      description: Service that create user
      summary: API for user creation
      operationId: createUser
      tags:
        - User
      requestBody:
        description: User body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    UserDTO:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: Edvard
        password:
          type: string
          example: qwerty1234
  responses:
    BadRequest:
      description: Bad Request
    InternalServerError:
      description: Internal Server Error
