name: Validate version

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'apis/**/api-first/metadata.yml'
      - 'apis/**/api-first/openapi-rest.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Set is_changed to true
        run: echo "is_changed=true" >> $GITHUB_ENV

      - name: Print change status
        run: |
          echo "Files changed: ${{ env.is_changed }}"
