name: Validate version

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for changes in `metadata.yml` and `openapi-rest.yml`
        id: check_changes
        run: |
          # Fetch the base branch and the head branch
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}

          # Check for changes in metadata.yml or openapi-rest.yml
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} -- 'apis/**/api-first/metadata.yml' 'apis/**/api-first/openapi-rest.yml')
          
          if [ -n "$CHANGED_FILES" ]; then
            echo "is_changed=true" >> $GITHUB_ENV
          else
            echo "is_changed=false" >> $GITHUB_ENV
          fi

      - name: Print and Store Changed File Directories
        if: env.is_changed == 'true'
        run: |
          CHANGED_DIRS=""
          for FILE in $(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} -- 'apis/**/api-first/metadata.yml' 'apis/**/api-first/openapi-rest.yml'); do
            DIR=$(dirname "$FILE")
            echo "Changed directory: $DIR"
            CHANGED_DIRS="$CHANGED_DIRS $DIR"
          done
          echo "CHANGED_DIRS=${CHANGED_DIRS}" >> $GITHUB_ENV

      - name: Print Changed Directories
        if: env.is_changed == 'true'
        run: |
          echo "Changed directories: $CHANGED_DIRS"
      
      
