name: Validate version

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for changes in `metadata.yml` and `openapi-rest.yml`
        id: check_changes
        run: |
          # Fetch the base branch and the head branch
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}

          # Check for changes in metadata.yml or openapi-rest.yml
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} -- 'apis/**/api-first/metadata.yml' 'apis/**/api-first/openapi-rest.yml')
          
          if [ -n "$CHANGED_FILES" ]; then
            echo "is_changed=true" >> $GITHUB_ENV
          else
            echo "is_changed=false" >> $GITHUB_ENV
          fi

      - name: Extract version information
        if: env.is_changed == 'true'
        run: |
          for FILE in $(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} -- 'apis/**/api-first/metadata.yml' 'apis/**/api-first/openapi-rest.yml'); do
            if [[ "$FILE" == *"openapi-rest.yml"* ]]; then
              OPENAPI_VERSION=$(grep 'info:' -A 3 "$FILE" | grep 'version:' | awk '{print $2}' | tr -d '\r')
              echo "OpenAPI version from $FILE: $OPENAPI_VERSION"
            elif [[ "$FILE" == *"metadata.yml"* ]]; then
              METADATA_VERSION=$(grep 'api.version:' "$FILE" | awk '{print $2}' | tr -d '\r')
              echo "Metadata API version from $FILE: $METADATA_VERSION"
            fi
          done
