name: Validate version

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch the base branch
        run: |
          git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

      - name: Check for changes in `metadata.yml` and `openapi-rest.yml`
        id: check_changes
        run: |
          # Check if any metadata.yml or openapi-rest.yml files were changed
          if git diff --name-only origin/${{ github.base_ref }} ${{ github.head_ref }} | grep -E 'apis/.+/api-first/(metadata.yml|openapi-rest.yml)'; then
            echo "is_changed=true" >> $GITHUB_ENV
          else
            echo "is_changed=false" >> $GITHUB_ENV
          fi

      - name: Print change status
        run: |
          echo "Files changed: ${{ env.is_changed }}"
