name: Validate versioon

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print Trigger Message
        run: echo "This workflow was triggered by a pull request!"