name: Maven CI for Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Ensure previous commit is available for comparison

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify GitHub Token Access
        run: |
          if [ -z "${{ secrets.APP_AFESOX }}" ]; then
            echo "ERROR: Secret APP_AFESOX is not set or not accessible."
            exit 1
          fi

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.APP_AFESOX }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Detect changed YAML files
        id: detect_yaml
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.yml$' | grep -v '^\.github/')
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No YAML files changed outside of .github directory."
            exit 0  # Exit gracefully if no relevant changes are detected
          fi
          
          echo "$CHANGED_FILES" > changed_files.txt

      - name: Extract Version, Name, and Process Executions
        run: |
          # Read changed files from the text file
          if [[ -f changed_files.txt ]]; then
            CHANGED_FILES=$(cat changed_files.txt)
            echo "Changed files: $CHANGED_FILES"
          else
            echo "No changed files detected."
            exit 1
          fi

          DEPLOYMENT_DONE=false

          # Loop through the changed files
          for FILE in $CHANGED_FILES; do
            if [[ $FILE == *"metadata.yml"* ]]; then
              echo "Processing $FILE..."

              # Check if the metadata.yml file exists and is readable
              if [[ ! -f $FILE ]]; then
                echo "File $FILE not found or not accessible. Skipping."
                continue
              fi

              # Extract version and name using yq
              VERSION=$(yq e '.api.version' $FILE)
              NAME=$(yq e '.api.name' $FILE)

              if [ -z "$VERSION" ] || [ -z "$NAME" ]; then
                echo "No version or name found in $FILE. Skipping."
                continue
              fi

              echo "Extracted Version: $VERSION"
              echo "Extracted Name: $NAME"

              ARTIFACT_ID="app-afesox-${NAME}-stable"
              export VERSION
              export ARTIFACT_ID
              export NAME

              # Extract all execution types from the metadata file
              EXECUTION_TYPES=$(yq e '.executions[].type' $FILE)
              if [ -z "$EXECUTION_TYPES" ]; then
                echo "No execution types found in $FILE. Skipping."
                continue
              fi

              echo "Execution types found: $EXECUTION_TYPES"

              # Loop through each execution type
              for EXECUTION_TYPE in $EXECUTION_TYPES; do
                echo "Processing execution type: ${EXECUTION_TYPE}"

                case $EXECUTION_TYPE in
                  client)
                    echo "Running client execution..."
                    mvn clean package -Dproject.version=${VERSION} -Pclient || exit 1
                    ;;
                  api-first)
                    echo "Running API-first execution..."
                    mvn clean package -Dproject.version=${VERSION} -Papi-first || exit 1
                    ;;
                  *)
                    echo "Unknown execution type: ${EXECUTION_TYPE}. Skipping."
                    continue
                    ;;
                esac

                # Attempt deployment
                if mvn deploy -Dproject.version=${VERSION} -Dpackage=${ARTIFACT_ID}; then
                  echo "Deployment of ${ARTIFACT_ID} with version ${VERSION} successful."
                  DEPLOYMENT_DONE=true
                else
                  echo "Deployment failed. Version ${VERSION} might already be deployed for ${ARTIFACT_ID}."
                  continue
                fi
              done
            else
              echo "File $FILE is not a metadata.yml. Skipping."
            fi
          done

          # If no deployments were done, print a message and exit with error
          if [ "$DEPLOYMENT_DONE" = false ]; then
            echo "No deployments were performed. Please check the changed files."
            exit 1
          fi
