name: Maven CI for Develop

on:
  pull_request:
    paths:
      - '**/*.yml'  # Trigger on any YAML file changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Ensure previous commit is available for comparison

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify GitHub Token Access
        run: |
          if [ -z "${{ secrets.APP_AFESOX }}" ]; then
            echo "ERROR: Secret APP_AFESOX is not set or not accessible."
            exit 1
          fi

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.APP_AFESOX }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Detect changed YAML files
        id: detect_yaml
        run: |
          # Detect changed YAML files, excluding any in the `.github` directory
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.yml$' | grep -v '^\.github/')
          echo "$CHANGED_FILES" > changed_files.txt

      - name: Check if openapi-rest.yml changed
        id: check_openapi
        run: |
          CHANGED_FILES=$(cat changed_files.txt)
          if echo "$CHANGED_FILES" | grep -q 'openapi-rest.yml'; then
            echo "openapi-rest.yml has changed."
            echo "OPENAPI_CHANGED=true" >> $GITHUB_ENV
          else
            echo "openapi-rest.yml has not changed."
            echo "OPENAPI_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Extract metadata and version
        id: extract_metadata
        run: |
          if [ "${{ env.OPENAPI_CHANGED }}" = "true" ]; then
            # Extract version and name from metadata.yml
            METADATA_FILE=$(echo "$CHANGED_FILES" | grep 'metadata.yml')
            if [ -f "$METADATA_FILE" ]; then
              VERSION=$(yq e '.metadata.version' "$METADATA_FILE")
              NAME=$(yq e '.metadata.name' "$METADATA_FILE")
              echo "Extracted version: $VERSION"
              echo "Extracted name: $NAME"
              echo "VERSION=$VERSION" >> $GITHUB_ENV
              echo "NAME=$NAME" >> $GITHUB_ENV

              # Create artifactId based on metadata
              ARTIFACT_ID="app-afesox-${NAME}-stable"
              echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
            else
              echo "Metadata file does not exist."
              exit 1
            fi
          else
            echo "Skipping metadata extraction as openapi-rest.yml did not change."
          fi

      - name: Build and Deploy with Maven
        run: |
          if [ -z "${{ env.VERSION }}" ] || [ -z "${{ env.NAME }}" ]; then
            echo "VERSION or NAME is not set correctly."
            exit 1
          fi

          echo "Deploying to artifactId: ${ARTIFACT_ID} with version: ${VERSION}"
          mvn clean package -Dproject.version=${VERSION}
          
          if mvn deploy -Dproject.version=${VERSION} -DartifactId=${ARTIFACT_ID}; then
            echo "Deployment successful."
          else
            echo "Deployment failed. Version ${VERSION} might already be deployed."
            exit 1
          fi
