name: Maven CI for Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Ensure previous commit is available for comparison

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify GitHub Token Access
        run: |
          if [ -z "${{ secrets.APP_AFESOX }}" ]; then
            echo "ERROR: Secret APP_AFESOX is not set or not accessible."
            exit 1
          fi

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.APP_AFESOX }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Detect changed YAML files
        id: detect_yaml
        run: |
          # Detect changed YAML files, excluding any in the `.github` directory
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.yml$' | grep -v '^\.github/')
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No YAML files changed outside of .github directory."
            exit 1
          fi
          
          # Output to a temporary file for further processing
          echo "$CHANGED_FILES" > changed_files.txt

      - name: Extract Version and Name from metadata.yml
        id: extract_metadata
        run: |
          # Read the changed files list from the temporary file
          CHANGED_FILES=$(cat changed_files.txt)
          
          # Initialize variables
          VERSION=""
          NAME=""

          for FILE in $CHANGED_FILES; do
            if [[ $FILE == *"metadata.yml"* ]]; then
              # Extract version and name from metadata.yml
              VERSION=$(yq e '.api.version' $FILE)
              NAME=$(yq e '.api.name' $FILE)
              break
            fi
          done

          # Export variables correctly using environment files
          if [ -z "$VERSION" ] || [ -z "$NAME" ]; then
            echo "No version or name found in the changed metadata files."
            exit 1
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "NAME=$NAME" >> $GITHUB_ENV

      - name: Update POM.xml with new artifactId and version
        run: |
          # Check if the variables are properly set
          if [ -z "${VERSION}" ] || [ -z "${NAME}" ]; then
            echo "VERSION or NAME is not set correctly."
            exit 1
          fi

          # Construct artifactId
          ARTIFACT_ID="app-afesox-${NAME}-stable"

          echo "Updating POM.xml with artifactId: ${ARTIFACT_ID} and version: ${VERSION}"

          # Update the POM file with the new artifactId and version
          sed -i "s/<artifactId>.*<\/artifactId>/<artifactId>${ARTIFACT_ID}<\/artifactId>/" pom.xml
          sed -i "s/<version>.*<\/version>/<version>${VERSION}<\/version>/" pom.xml

      - name: Build and Deploy with Maven
        run: |
          echo "Deploying to package: ${ARTIFACT_ID} with version: ${VERSION}"
          mvn clean package -Dproject.version=${VERSION}
          
          if mvn deploy -Dproject.version=${VERSION} -DartifactId=${ARTIFACT_ID}; then
            echo "Deployment successful."
          else
            echo "Deployment failed. Version ${VERSION} might already be deployed."
            exit 1
          fi
