name: Execute Deploy

on:
  workflow_dispatch:
    inputs:
      EXTRACTED_VERSION:
        description: 'Version extracted from the file'
        required: true
      EXTRACTED_NAME:
        description: 'Name extracted from the file'
        required: true
      EXTRACTED_EXECUTION:
        description: 'Execution type extracted from the file'
        required: true

jobs:
  execute-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Ensure previous commit is available for comparison

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.APP_AFESOX }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Deploy Maven Artifact
        run: |
          ARTIFACT_ID="app-afesox-${{ github.event.inputs.EXTRACTED_NAME }}-${{ github.event.inputs.EXTRACTED_EXECUTION }}-stable"
          echo "Deploying ${{ github.event.inputs.EXTRACTED_NAME }} with artifact ID ${ARTIFACT_ID}, version ${{ github.event.inputs.EXTRACTED_VERSION }}, and execution type ${{ github.event.inputs.EXTRACTED_EXECUTION }}..."

          # Run Maven build for the current execution
          mvn clean package -P${{ github.event.inputs.EXTRACTED_EXECUTION }} -Dproject.version=${{ github.event.inputs.EXTRACTED_VERSION }}
          
          # Run Maven deploy for the current execution
          if mvn deploy -P${{ github.event.inputs.EXTRACTED_EXECUTION }} -Dproject.version=${{ github.event.inputs.EXTRACTED_VERSION }} -Dpackage=${ARTIFACT_ID}; then
            echo "Deployment of ${ARTIFACT_ID} with version ${{ github.event.inputs.EXTRACTED_VERSION }} for execution type ${{ github.event.inputs.EXTRACTED_EXECUTION }} successful."
          else
            echo "Deployment failed. Version ${{ github.event.inputs.EXTRACTED_VERSION }} might already be deployed for ${ARTIFACT_ID}."
          fi