name: Verify OpenAPI Files on PR

on:
  pull_request:
    branches:
      - develop

jobs:
  validate-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Only fetch the current commit

      - name: Install swagger-cli
        run: |
          npm install -g @apidevtools/swagger-cli

      - name: Validate OpenAPI files
        run: |
          # Find all openapi.yml files in the repository
          OPENAPI_FILES=$(find . -type f -name 'openapi.yml')

          if [ -z "$OPENAPI_FILES" ]; then
            echo "No OpenAPI files found to validate."
            exit 0  # Exit with 0 to avoid
