name: Validate OpenAPI Files

on:
  pull_request:
    paths:
      - '**/openapi-rest.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli

      - name: Check Spectral version
        run: spectral --version

      - name: Validate OpenAPI files
        run: |
          CHANGED_OPENAPI_FILES=$(find . -type f -name 'openapi-rest.yml')
          for file in $CHANGED_OPENAPI_FILES; do
            echo "Validating $file with Spectral..."
            spectral lint "$file" --ruleset .spectral.yaml || exit 1
          done