name: Generate Message on Comment

on:
  issue_comment:
    types: [created]

jobs:
  print-message:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/generate') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse command and extract name
        id: parse-command
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
          echo "::set-output name=api_name::$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--name ")[^"]*')"

      - name: List current directory
        run: |
          echo "Listing contents of the current directory:"
          ls -la
          echo "Listing contents of the apis directory:"
          ls -la ./apis

      - name: Read metadata and find api-spec-type
        id: find-api-spec
        run: |
          api_name="${{ steps.parse-command.outputs.api_name }}"
          echo "Looking for API name: $api_name"
          api_spec_type=$(yq eval ".apis[] | select(.name == \"$api_name\") | .api-spec-type" ./apis/metadata.yml)
          echo "Found api-spec-type: $api_spec_type"
          echo "::set-output name=api_spec_type::$api_spec_type"

      - name: Print api-spec-type
        run: |
          echo "API Spec Type: ${{ steps.find-api-spec.outputs.api_spec_type }}"
