name: Print Message on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Print to stacktrace
        run: |
          echo "===== Printing to stacktrace 111111====="
          echo "This is a custom message triggered by the PR."
          echo "===== End of stacktrace ====="
