name: Generate Message on Comment

on:
  issue_comment:
    types: [created]

jobs:
  generate-message:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/generate' }}
    runs-on: ubuntu-latest
    steps:
      - name: Post comment to PR
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const run_id = process.env.GITHUB_RUN_ID;
            const repo = context.repo;
            const workflow_run_url = `https://github.com/${repo.owner}/${repo.repo}/actions/runs/${run_id}`;
            
            const comment_body = `
            ### Workflow Execution
            - **Job Status:** Success
            - **[View Workflow Run](${workflow_run_url})**
            `;
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: issue_number,
              body: comment_body,
            });
