name: Generate Message on Comment

on:
  issue_comment:
    types: [created]

jobs:
  print-message:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/generate') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Post initial comment with workflow link
        id: post-initial-comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const run_id = process.env.GITHUB_RUN_ID;
            const repo = context.repo;
            const workflow_run_url = `https://github.com/${repo.owner}/${repo.repo}/actions/runs/${run_id}`;
            
            const comment_body = `
            ### Workflow Execution Started
            - **Job Status:** In Progress
            - **[View Workflow Run](${workflow_run_url})**
            `;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: issue_number,
              body: comment_body,
            });

      - name: Parse command and extract name
        id: parse-command
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
          echo "::set-output name=api_name::$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--name ")[^"]*')"

      - name: Read metadata and find definition-path
        id: find-definition-path
        run: |
          api_name="${{ steps.parse-command.outputs.api_name }}"
          echo "Looking for API name: $api_name"
          definition-path=$(yq eval ".apis[] | select(.name == \"$api_name\") | .definition-path" ./apis/metadata.yml)
          echo "Found definition-path: $definition-path"
          echo "::set-output name=definition-path::$definition-path"

      - name: Print api-spec-type
        run: |
          echo "API Spec Type: ${{ steps.find-api-spec.outputs.definition-path }}"
