name: Generate Message on Comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/generate') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the pull request branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
          fetch-depth: 0

      - name: Fetch pull request SHA and checkout
        run: |
          git fetch origin ${{ github.event.issue.pull_request.head.sha }} --depth=1
          git checkout ${{ github.event.issue.pull_request.head.sha }}

      - name: Post initial comment with workflow link
        id: post-initial-comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const run_id = process.env.GITHUB_RUN_ID;
            const repo = context.repo;
            const workflow_run_url = `https://github.com/${repo.owner}/${repo.repo}/actions/runs/${run_id}`;
            
            const comment_body = `
            ### Workflow Execution Started
            - **Job Status:** In Progress
            - **[View Workflow Run](${workflow_run_url})**
            `;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: issue_number,
              body: comment_body,
            });

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify GitHub Token Access
        run: |
          if [ -z "${{ secrets.APP_AFESOX }}" ]; then
            echo "ERROR: Secret APP_AFESOX is not set or not accessible."
            exit 1
          fi

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.APP_AFESOX }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Parse command and extract name
        id: parse-command
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
          api_name=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--name ")[^"]*')
          echo "::set-output name=api_name::$api_name"

      - name: Extract ticket number from PR title
        id: extract-ticket-num
        run: |
          pr_title="${{ github.event.issue.title }}"
          
          # Check for the presence of brackets
          if [[ ! "$pr_title" =~ \[.*\] ]]; then
            echo "ERROR: Pull Request title must have the correct format [SITIONIX-*] description."
            exit 1
          fi

          # Extract and format the ticket number
          ticket_num=$(echo "$pr_title" | grep -oP '(?<=\[)[^]]*(?=\])' | tr '[:upper:]' '[:lower:]')

          # Replace any forward slashes with hyphens
          ticket_num=$(echo "$ticket_num" | tr '/' '-')
          
          echo "::set-output name=ticket_num::$ticket_num"

      - name: Read metadata and find api-spec-type and definition-path
        id: find-api-spec
        run: |
          api_name="${{ steps.parse-command.outputs.api_name }}"
          echo "Looking for API name: $api_name"
          api_spec_type=$(yq eval ".apis[] | select(.name == \"$api_name\") | .api-spec-type" ./apis/metadata.yml)
          definition_path=$(yq eval ".apis[] | select(.name == \"$api_name\") | .definition-path" ./apis/metadata.yml)
          echo "Found api-spec-type: $api_spec_type"
          echo "Found definition-path: $definition_path"
          echo "::set-output name=api_spec_type::$api_spec_type"
          echo "::set-output name=definition_path::$definition_path"

      - name: Read additional metadata from definition-path
        id: read-definition-metadata
        run: |
          definition_path="${{ steps.find-api-spec.outputs.definition_path }}"
          metadata_file="./apis/${definition_path}/metadata.yml"
          version=$(yq eval '.api.version' $metadata_file)
          name=$(yq eval '.api.name' $metadata_file)

          echo "Found version: $version"
          echo "Found name: $name"
          echo "::set-output name=api_version::$version"
          echo "::set-output name=api_name::$name"

      - name: Export Environment Variables
        run: |
          echo "VERSION=${{ steps.read-definition-metadata.outputs.api_version }}" >> $GITHUB_ENV
          echo "NAME=${{ steps.read-definition-metadata.outputs.api_name }}" >> $GITHUB_ENV
          echo "ARTIFACT_ID=app-afesox-${{ steps.read-definition-metadata.outputs.api_name }}-${{ steps.find-api-spec.outputs.api_spec_type }}-${{ steps.extract-ticket-num.outputs.ticket_num }}-unstable" >> $GITHUB_ENV
          echo "API_SPEC_TYPE=${{ steps.find-api-spec.outputs.api_spec_type }}" >> $GITHUB_ENV

      - name: Package the Project
        run: |
          mvn clean package -P${{ env.API_SPEC_TYPE }} -Dproject.version=${{ env.VERSION }} -Dmaven.wagon.http.ssl.insecure=true || exit 1

      - name: Remove Package
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.APP_AFESOX }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/user/packages/maven/com.afesox.$ARTIFACT_ID"

      - name: Deploy the Project
        run: |
          mvn deploy -P${{ env.API_SPEC_TYPE }} -Dproject.version=${{ env.VERSION }} -Dpackage=${{ env.ARTIFACT_ID }} -Dmaven.wagon.http.ssl.insecure=true || exit 1

      - name: Construct Maven Dependency String
        id: construct-dependency
        run: |
          dependency_string="<dependency>\n  <groupId>com.afesox</groupId>\n  <artifactId>${{ env.ARTIFACT_ID }}</artifactId>\n  <version>${{ env.VERSION }}</version>\n</dependency>"
          echo "::set-output name=dependency_string::$dependency_string"

      - name: Post Maven Dependency as Comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const dependency_string = '${{ steps.construct-dependency.outputs.dependency_string }}';
            const comment_body = `
            ### Maven Dependency
            \`\`\`xml
            ${dependency_string}
            \`\`\`
            `;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: issue_number,
              body: comment_body,
            });

      - name: Check for Job Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const failure_comment = `
            ### Workflow Execution Failed
            - **Job Status:** Failed
            `;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: issue_number,
              body: failure_comment,
            });
