name: Print Message on Comment

on:
  issue_comment:
    types: [created]

jobs:
  print-message:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/print-message' }}
    runs-on: ubuntu-latest
    steps:

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Post message back to PR
        run: |
          gh pr comment ${{ github.event.issue.number }} --body "This is a message from the action. The message: 'This is a custom message triggered by the '/print-message' comment.'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
