name: Trigger on Comment

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    if: |
      contains(github.event.comment.body, '/generate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Another Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'other-workflow.yml'
          ref: ${{ github.event.issue.pull_request.head.sha }}
