name: Trigger on "/generate" in Commit Message

on:
  push:
    branches:
      - main
      - develop

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get commit message
        id: commit_message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check if the commit message contains "/generate"
        if: contains(env.COMMIT_MESSAGE, '/generate')
        run: echo "The commit message contains '/generate'. Running the next steps..."

      # Add your steps here that should run when "/generate" is found
      - name: Run your script or action
        if: contains(env.COMMIT_MESSAGE, '/generate')
        run: echo "This is where you would run your script or action."
