name: Print Comment on /generate

on:
  issue_comment:
    types: [created]  # Trigger on creation of new comments

jobs:
  log-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Log comment content
        run: echo "Comment: ${{ github.event.comment.body }}"

      - name: Check for /generate in the comment
        if: startsWith(github.event.comment.body, '/generate')
        run: echo "The comment contains '/generate'. Workflow triggered successfully!"
