name: pull request comment

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')  # Check if the comment is from a pull request, exclude those from an issue.
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        if: contains(github.event.comment.body, '/support')  # Check if the comment contains the keyword "/support"
        run: |
          echo "say hello"

      - name: test
        if: contains(github.event.comment.body, '/test')  # Check if the comment contains the keyword "/test"
        run: |
          echo "test"
