name: Trigger on "/generate" in PR Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-comment:
    if: github.event.issue.pull_request != null  # Ensure it's a PR comment
    runs-on: ubuntu-latest
    steps:
      - name: Check if the comment starts with "/generate"
        if: startsWith(github.event.comment.body, '/generate')
        run: echo "The comment starts with '/generate'. Running the next steps..."

      - name: Run your script or action
        if: startsWith(github.event.comment.body, '/generate')
        run: echo "This is where you would run your script or action."
