name: Print Comment on /generate

on:
  issue_comment:
    types:
      - created  # List items should be on separate lines

jobs:
  log-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Log comment content
        run: |
          echo "Comment: ${{ github.event.comment.body }}"

      - name: Check for /generate in the comment
        if: startsWith(github.event.comment.body, '/generate')
        run: |
          echo "The comment contains '/generate'. Workflow triggered successfully!"
